### ISSUE TITLE
Esc to close the floating window (similar functionality as telescope.nvim)

### ISSUE THREAD

**Issue by akshit-sharma** [rmagatti/goto-preview#101]
**Is your feature request related to a problem? Please describe.**
Feature for adding an ability to close the existing float window by pressing `<Esc>`.

**Describe the solution you'd like**
Ability of closing float window by pressing `<Esc>`.  If multiple windows are opened then the windows close same in stack fashion (last in first out).

**Describe alternatives you've considered**
Right now, the floating windows can be closed by `:q<CR>` or all of them by `gP`.

**Additional context**
I am trying to get the same intuition for closing the floating window as given by `telescope.nvim`. It currently closes via <C-c> and <Esc> (if in normal mode).

**Comment by rmagatti** [comment]
Hey, as mentioned before a few times, I'm not down to adding this as built-in. You can use hooks to get the behaviour you want though. 
https://github.com/rmagatti/goto-preview/issues/61#issuecomment-1130194398

Cheers!
