### ISSUE TITLE
[FEATURE] add `post_close_hook` option which executes after `close_all_win()`

### ISSUE THREAD

**Issue by benelan** [rmagatti/goto-preview#102]
**Is your feature request related to a problem? Please describe.**

I want to disable a couple things in the previews that only have a global on/off switch rather than for a specific window or buffer (e.g. [`TSContextDisable`](https://github.com/nvim-treesitter/nvim-treesitter-context#commands)). I can do so with the `post_open_hook`, but when I close all of the preview windows using `close_all_win()`, the treesitter context is obviously still disabled. It would be convienent to have a hook that runs after closing the previews so I can execute `TSContextEnable`.

**Describe the solution you'd like**

A new `post_close_hook` option which executes after `close_all_win()`. It could potentially execute when closing the preview buffers normally too using autocommands and window numbers, but that's extra credit points.

**Describe alternatives you've considered**

I created my own keymap that executes a function with `close_all_win()` and other things I want to do. But having a built in way to do it would be nice so I could just use the default keymaps.

**Additional context**

This is low priority since there is an easy workaround, but it also seems relatively low effort. I'd be happy to add the feature myself if it is something you support.

**Comment by rmagatti** [comment]
Hey, thanks for taking the time to submit the issue! This sounds like a good addition, I can get to it at some point or would welcome a PR otherwise!

**Comment by TJ-Adams** [comment]
I made a pull request here which should get you what you're looking for @benelan.
