### ISSUE TITLE
[BUG] incorrect floating window closed in case multiple floating previews are opened

### ISSUE THREAD

**Issue by embe221ed** [rmagatti/goto-preview#116]
**Describe the bug**
I noticed that the change implemented in #115 made neovim close incorrect floating preview window. In case I have two floating windows open, `:q` will close the second one instead of the current floating window.

**To Reproduce**
1. go-to definition preview
2. from the floating window open another definition preview
3. try to close the newest floating window

**Expected behavior**
the currently focused floating window is closed

**Screenshots**

**Baseline (please complete the following information):**
 - OS. e.g `uname -a`: MacOS
 - Neovim version `nvim --version`: `NVIM v0.10.0-dev-2422+g0760d9868`
 - URL to your current config (if public): https://github.com/embe221ed/scripts/tree/main/configs/nvim

**Comment by embe221ed** [comment]
commenting out the code from #115 fixes the issue for me

**Comment by rmagatti** [comment]
@Tebro have you experienced the issue above at all?

**Comment by Tebro** [comment]
I have not seen this, but I use `<C-w>c` to close windows. I however just tested using `:q` instead and I cannot reproduce.

**Comment by rmagatti** [comment]
For the record, I can't reproduce this either. I'm on MacOS and Neovim built from master.

**Comment by rmagatti** [comment]
Stale
