### ISSUE TITLE
[BUG] Goto implementation not working

### ISSUE THREAD

**Issue by kantog** [rmagatti/goto-preview#123]
I don't know if this is something I just haven't found yet, but every time I want to jump to a function definition in another file, it brings me to my header file (see screenshot), from which my current file obviously gets the function. Is there a way to not go to the header file, but to the actual file with the function itself?
![Screenshot from 2024-09-07 17-40-13](https://github.com/user-attachments/assets/dd901a35-c439-4fc1-8f2c-7172fb4035a2)

**Comment by rmagatti** [comment]
You've probably been using the go to definition function, you need to use the go to implementation function instead

**Comment by kantog** [comment]
I was thinking something similar, but the go to implementation function doesn't seem to do anything for me. Any Idea why that could be? I am using lsp-zero with mason.

**Comment by rmagatti** [comment]
No, but this wouldn't be a `goto-preview` issue necessarily. Can you go to implementation with your lsp outside of calling goto-preview? All goto-preview does is invoke the LSP's `textDocument/implementation`. So if that's not going anywhere for you, maybe that's not supported by your LSP?

Do you see a `print("goto-preview: Error calling LSP" + lsp_call + ". The current language lsp might not support it.")` log anywhere?

**Comment by kantog** [comment]
Update: I think it is a Makefile issue, and not an lsp issue. Apparently, Makefile doesn't provide the right information for the lsp to navigate projects correctly.

**Comment by rmagatti** [comment]
@kantog feel free to post any more useful information here for others but as this doesn't really look like a plugin issue I'll close this here.
