### ISSUE TITLE
goto-preview does not work

### ISSUE THREAD

**Issue by supermanc88** [rmagatti/goto-preview#14]
my config:

call plug#begin('~/.nvim-config/plugged')
...
" https://github.com/rmagatti/goto-preview
Plug 'rmagatti/goto-preview'
...
" https://github.com/neoclide/coc.nvim
Plug 'neoclide/coc.nvim', {'branch': 'release'}
...
call plug#end()

...

lua <<EOF
require('goto-preview').setup {
}
EOF

I can't open the floating window in the CPP file.

**Comment by supermanc88** [comment]
I solved this problem, this plugin requires built-in LSP, So I need to install neovim/nvim-lspconfig

**Comment by rmagatti** [comment]
Ah yes, actually this is something I should probably mention more clearly in the readme. I'll add something up, thanks!

**Comment by rmagatti** [comment]
https://github.com/rmagatti/goto-preview/commit/5a7a6285ad59cfee9dbb976e4a032e7545d14954
