### ISSUE TITLE
Ability to open current preview in split

### ISSUE THREAD

**Issue by tami5** [rmagatti/goto-preview#16]
Hey @rmagatti, awesome plugin, I love it. Thanks a lot for your time in developing it.

Sometimes I maybe previewing something and I want to "zoom in". It would be nice to do something like <C-w>v and have the buffer registered in my tab line.

Additionally, as noted with the positioning bug, yes the popup go all over the place. However, it might be worth it to take  [vscode/preview popup](https://www.reddit.com/r/programming/comments/n99kv1/inliner_pull_blocks_of_code_into_a_single_file/?utm_medium=android_app&utm_source=share) approach and let them stack under each other.

Any ways thanks again

**Comment by rmagatti** [comment]
Hey @tami5 sorry about the delay, I think your suggestion is good. That said I think it's also already possible. I'll show you a few examples in a bit and you can let me know if that's not the case

**Comment by rmagatti** [comment]
> Ability to open current preview in split  

You can use regular window movement bindings like `<C-w>L` to get the floating window to become a normal split.
https://user-images.githubusercontent.com/2881382/123523144-19faf580-d67f-11eb-861e-e5b42394d33e.mp4

> Additionally, as noted with the positioning bug, yes the popup go all over the place. However, it might be worth it to take vscode/preview popup approach and let them stack under each other.

The positioning is very deliberate with this plugin, where the floats do actually stack not directly under an existing floag position but under the cursor so one can easily track where they triggered the preview window from.

**Comment by rmagatti** [comment]
I've also been using this patch from @andrew-pa for a few days now and the positioning has been fixed for me since.
https://github.com/neovim/neovim/pull/14770

**Comment by tami5** [comment]
thanks @rmagatti . Hopefully that patch will be merged soon. Also, is there any way to identify the goto-preview buffer, I want to attach mappings to it.

**Comment by rmagatti** [comment]
@tami5 You can use the `post_open_hook` like this to set keybindings.
<img width="607" alt="Screen Shot 2021-06-27 at 2 00 17 AM" src="https://user-images.githubusercontent.com/2881382/123537200-7562cd00-d6eb-11eb-9be6-87b04e9d6a72.png">

**Comment by tami5** [comment]
😍 😍 😍 😍 😍  amazing @rmagatti I don't know that existed. Honestly, great design

**Comment by oda-winston** [comment]
Here is an example with the vertical split

```
require("goto-preview").setup({
  post_open_hook = function(buffer, _)
    vim.api.nvim_buf_set_keymap(buffer, "n", "<C-V>", "<C-W>L", { noremap = true })
  end,
})
```

**Comment by isurfbecause** [comment]
Here is an example with the vertical and horizontal split

```
require("goto-preview").setup({
  post_open_hook = function(buffer, _)
    -- Vert split/Move to right
    vim.api.nvim_buf_set_keymap(buffer, "n", "v", "<C-W>L", { noremap = true })
    -- Split down/move to bottom
    vim.api.nvim_buf_set_keymap(buffer, "n", "s", "<C-W>J", { noremap = true })
  end,
})
```
