### ISSUE TITLE
`post_open_hook` not working for buffers opened in preview window

### ISSUE THREAD

**Issue by sahilsehwag** [rmagatti/goto-preview#17]
**Current behavior**
If we open another buffer in the current preview window (_like LSP's goto-definition_), then `post_open_hook` won't be called for the new buffer opened in the same preview window.

**Expected behavior**
If we open/jump to another buffer from within preview-window then `post_open_hook` should be called for the new buffer, Hence the code executed in the hook(_like creating buffer local mappings_) will be retained.

**Comment by rmagatti** [comment]
Hey, so this is kind of hard. When you do a goto-definition from inside a preview buffer, that's just an open buffer action, the plugin doesn't track opening a buffer (and admittedly I wouldn't know where to start with doing that).

The `post_open_hook` only really gets triggered when a preview gets triggered to open. Anything else you do in a preview buffer isn't really part of the plugin's flow anymore at all.

What you can try doing is probably, setting an autocmd for `BufEnter` or something similar that sets your local mappings get triggered there.

I'm not sure this is the solution you're looking for but to be honest it would be kind of hard to do what you're describing. I'd be happy to look into a PR to try and do this though

**Comment by sahilsehwag** [comment]
`BufEnter `would then set the mappings for all the buffers, I think we can do this in the plugin, since we already track all the open preview windows (since we need to close them), therefore we have the window ids, and whenever `BufEnter` is triggered we can check if currently active window is one of the open preview window or not and the execute the `post_open_hook`

**Comment by rmagatti** [comment]
Yeah I think your idea should work.
I'd be happy to review a PR for this, but I probably won't be able to work on it myself in the next couple of days.

**Comment by rmagatti** [comment]
@sahilsehwag this took a while but I finally got to it. Should be fixed now.
