### ISSUE TITLE
Support for references preview

### ISSUE THREAD

**Issue by MatthiasX86** [rmagatti/goto-preview#18]
Firstly... love this plugin. I realize support for references would perhaps entail some extra UI for cycling through the different references with something like a preview window for the locations but I think this would be a shoe-in for this awesome plugin given what it can do already.

**Comment by rmagatti** [comment]
Yeah so this is a great idea, I'd have to put some thought into how to get the right UI for it though like you mentioned.
Definitely open to suggestions or even better, PRs 😊.

Thanks for the submission @MatthiasX86, much appreciated!

**Comment by rmagatti** [comment]
@MatthiasX86 followup question here, what would you expect to happen after selecting a reference from a list? For it to open a preview floating window like it normally does? If so, anchored to what exactly? Maybe the initial cursor position of when you triggered the references preview?

**Comment by rmagatti** [comment]
@MatthiasX86 implemented in #22.
It uses telescope to cycle through the references. Let me know if this works for you or if this wasn't what you had in mind.
