### ISSUE TITLE
Getting `attempt to index field 'lsp_configs' (a nil value)`

### ISSUE THREAD

**Issue by andersevenrud** [rmagatti/goto-preview#23]
Hi,

Just caught your (?) post on reddit, and this is something I have been looking for as an alternative to lsputils or lspsaga. All I want is the preview, so this is good stuff.

However, after setting up I get the following error:

```
Error executing vim.schedule lua callback: .../pack/packer/start/goto-preview/lua/goto-preview/lib.lua:120: attempt to index field 'lsp_configs' (a nil value)
```

I used the (minimal) setup instructions from the README. And I've double checked that it's 1:1.

Edit: 

* Tested with TypeScript- and Vue LSP
* Commit 5b9c7f2d312e2715d9a5e86b6a5bbd6b9f1b406a
* Neovim from source

```
NVIM v0.6.0-dev+253-ge31652879
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by n3wborn** [comment]
Same for me with default config

**Comment by hlmtre** [comment]
+1 to this.
`NVIM v0.6.0-dev+205-g9695691ee`.

**Comment by hlmtre** [comment]
Hey guys, found (a? the?) fix. The default chunk has to be initialized somewhere (I stuck mine in `init.lua`, which loads the rest of my stuff). That's combined with the setup in `packer.nvim`.
```
-- init.lua, sourced in my nvim startup
require('goto-preview').setup {
    width = 120; -- Width of the floating window
    height = 15; -- Height of the floating window
    default_mappings = false; -- Bind default mappings
    debug = false; -- Print debug information
    opacity = nil; -- 0-100 opacity level of the floating window where 100 is fully transparent.
    post_open_hook = nil -- A function taking two arguments, a buffer and a window to be ran as a hook.
  }
```

**Comment by rmagatti** [comment]
I'll check this out soon, thanks for trying the plugin out and for the issue submission!

**Comment by hlmtre** [comment]
FURTHER STILL. This works correctly. I guess the defaults don't get set correctly.
in `plugins.lua` (your `packer` config):
```
 use {
    'rmagatti/goto-preview',
    config = function()
~   ¦ require('goto-preview').setup {
+   ¦ ¦ width = 120; -- Width of the floating window
+   ¦ ¦ height = 15; -- Height of the floating window
+   ¦ ¦ default_mappings = true; -- Bind default mappings
+   ¦ ¦ debug = false; -- Print debug information
+   ¦ ¦ opacity = nil; -- 0-100 opacity level of the floating window where 100 is fully transparent.
+   ¦ ¦ post_open_hook = nil -- A function taking two arguments, a buffer and a window to be ran as a hook.
+   ¦ }
    end
    }
```

**Comment by chuwy** [comment]
Thanks, @hlmtre! Setting it up with explicit defaults worked out! (Not even using packer)

**Comment by andersevenrud** [comment]
Ah, no wonder. The setup function doesn't run if you supply an empty table :D

https://github.com/rmagatti/goto-preview/blob/9968354d84d100dbd07b771a5ddeb3aa72c83be2/lua/goto-preview.lua#L27-L35

**Comment by rmagatti** [comment]
Ah, that's definitely an oversight on my part, I should allow empty setup calls. Thanks for digging into this!
