### ISSUE TITLE
Doesn't work with ZenMode

### ISSUE THREAD

**Issue by chuwy** [rmagatti/goto-preview#24]
I'm using this distraction-free plugin: https://github.com/folke/zen-mode.nvim

If I try to open goto-preview while `ZenMode` is activated - I don't see a popup window, but my cursor is constrained within some invisible border, in other words it seems the window exists, but it's completely transparent. If a type `:bd` my cursor gets back to normal.

**Comment by rmagatti** [comment]
@chuwy I pushed a change just now that should help at least with the initial preview, the behaviour is still not 100% but I think it might be outside of the scope of this plugin to fix. Try it out, hope it's at least better now.
