### ISSUE TITLE
Make Telescope an optional dependency

### ISSUE THREAD

**Issue by Bruflot** [rmagatti/goto-preview#26]
I'm not particularly fond of Telescope as a whole, so it would be great if Telescope could be an optional dependency. I'm currently stuck using an older version of `goto-preview` because the more recent versions require Telescope.

**Comment by rmagatti** [comment]
@Bruflot fair point. In that case, to start with at least I would basically expose an option to disable the references preview, since that option requires cycling through references. I could later experiment with just piping the lsp references result into the quickfix list as an option too.
