### ISSUE TITLE
close_all_win() is not working

### ISSUE THREAD

**Issue by cseickel** [rmagatti/goto-preview#29]
It is just me, or does this function not do anything? I just installed this plugin a few days ago so I can't say if it used to work and just broke on a recent commit, but it definitely does not do anything right now. I am using this command to test it:

`lua require('goto-preview').close_all_win() `

**Comment by rmagatti** [comment]
Hi @cseickel I'll need some more info to better understand what can be happening for you. It works perfectly fine for me here. Could you enable debug logs, then paste whatever results you get from running that here?

**Comment by cseickel** [comment]
I took a deeper look because there were no debug statements from the close_all_win method. It seem to be a scope issue, where the lib.windows variable is being set correctly when opening windows, but it is always empty when accessed from the main module. I moved the close_all_win method to the lib module and called it from there and it worked fine.

I'm not sure why it works differently for me. Now that i know what it is I'll do some more troubleshooting and put in a PR to fix the issue.
