### ISSUE TITLE
LSP Documentation not showing in first try

### ISSUE THREAD

**Issue by marcelarie** [rmagatti/goto-preview#34]
![nvim-goto-prev](https://user-images.githubusercontent.com/62728887/137618887-b404f6c0-4c13-45af-9208-3038d7bd0922.gif)
When using LSP with `rust-analyzer`, the docs that appear with `Shift+k` opens behind the `goto-preview` window.

nvim -v `NVIM v0.6.0-dev+464-g1ced6cf08`

**Comment by rmagatti** [comment]
@marcelarie this PR I just merged starts setting the zindex explicitly again and should fix your issue.

The reason is because if I don't, Neovim sets the zindex of any floating window without an explicit zindex to 50
https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp/util.lua#L1010

**Comment by marcelarie** [comment]
😁 thank you!
