### ISSUE TITLE
[BUG] attempt to index local 'data' (a nil value)

### ISSUE THREAD

**Issue by jlesquembre** [rmagatti/goto-preview#37]
**Describe the bug**

`lua require('goto-preview').goto_preview_definition()` returns an error:

```
Error executing vim.schedule lua callback: ...ack/home-manager/start/goto-preview/lua/goto-preview.lua:14: attempt to index local 'data' (a nil value)
```
but `lua vim.lsp.buf.definition()` works properly. 

Manually executing `vim.lsp.buf_request, 0, "textDocument/implementation", vim.lsp.util.make_position_params()` seems to return valid data, e.g.:

```
<function 1> 0 "textDocument/implementation" {
  position = {
    character = 34,
    line = 344
  },
  textDocument = {
    uri = "file:///.../views.cljs"
  }
}
```

The issue is happening with `clojure-lsp`, with `typescript-lsp` goto-preview seems to work ok, but I don't get the reason for that

**Baseline (please complete the following information):**
 - OS. e.g `uname -a`: `Linux 5.10.76 #1-NixOS SMP Wed Oct 27 07:56:57 UTC 2021 x86_64 GNU/Linux`
 - Neovim version `nvim --version`:
```
NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3
Compilation:
Compiled by nixbld

Features: +acl +iconv +tui
```
 - URL to your current config (if public): https://github.com/jlesquembre/dotfiles/blob/master/dotfiles/neovim/lspconfig.lua

**Comment by rmagatti** [comment]
Hey @jlesquembre, are you calling `goto_preview_implementation` or `goto_preview_definition`? The manual call to the LSP snippet you show calling the implementation one, does that also not work with goto-preview or is it just the definition call that doesn't?

**Comment by jlesquembre** [comment]
I'm calling `goto_preview_definition`. I tested `goto_preview_implementation`, which doesn't show any error, but does nothing.

The LSP snippet I posted, I think it is what goto-preview is calling internally. That snippet works fine, it's only goto-preview not working. I'm confused by that, since the LSP seems to return a valid value.

**Comment by rmagatti** [comment]
@jlesquembre So from what I can tell there are a few odd things here
1. I think the clojure LSP doesn't seem to support `textDocument/implementation`, at least according to https://github.com/clojure-lsp/clojure-lsp/blob/master/docs/capabilities.md, so it is odd to me how you seem to have called that manually and got results for it. (might just be out of date docs idk)
2. There is a thing called a legacy_handler I added a while back, this was to conform to the new way Neovim sends the data through from the LSP call to the registered handler - it might be that that logic is not working well enough when in conjunction with clojure-lsp. What I mean by that is the only real way `data` could be `nil` is if this line `local data = result[1]` returned nil, which could happen depending on what came back from the lsp call.

I have created this PR which should help with identifying what is wrong through improved logging.
https://github.com/rmagatti/goto-preview/pull/40

Would you mind updating `goto-preview` to the newest version, enabling debug, `require'goto-preview'.setup{debug=true}` and then showing me what you get?

**Comment by jlesquembre** [comment]
@rmagatti thanks for your help, with the latest version, that is the debug message I get:

```
goto-preview: calling new handler
goto-preview: nil
Error executing vim.schedule lua callback: ...ack/home-manager/start/goto-preview/lua/goto-preview.lua:15: attempt to index local 'data' (a nil value)
```

I'll try to do some debugging on my own

**Comment by jlesquembre** [comment]
found something, the `result` value is something like
```
{
  range = {
    end = {
      character = 18,
      line = 36
    },
    start = {
      character = 6,
      line = 36
    }
  },
  uri = "file:///.../utils.cljc"
}
```

it is not an array, because of that, `result[1]` is nil.

Not sure if what clojure lsp returns is valid according to the lsp spec

**Comment by jlesquembre** [comment]
I was looking to the LSP specification, looks like returning a single `Location` is a valid response:
https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_definition

Maybe we could do something like `local data = result[1] or result` ?

**Comment by rmagatti** [comment]
Yeah that should work! I did not realize a single location was a thing. I'll see if I can get to this soon, if not happy to review a PR for it too.

**Comment by jlesquembre** [comment]
here you go: #41 

I took a deeper look, and I think that's the only required changed

**Comment by rmagatti** [comment]
Nice, thanks @jlesquembre!

**Comment by lougreenwood** [comment]
I also see this error when trying to `goto_preview_definition()` in a ts file. I see the error and the preview window is successful shown.

I'm new to vim and not quite sure how to help with a reproduction etc...

**Comment by lougreenwood** [comment]
I also get the same error with the `ember` language server if a definition does not exist.

**Comment by rmagatti** [comment]
@lougreenwood got a video or something showing what you mean? I can't reproduce this with tsserver.
