### ISSUE TITLE
[Feature] A function to open the currently opened position in a new buffer

### ISSUE THREAD

**Issue by elkowar** [rmagatti/goto-preview#38]
It would be cool if there'd be an easy way to set up a keybind that "expands" the popup window and opens the displayed location in a new buffer!

**Comment by rmagatti** [comment]
This comes up every now and then. You can just take advantage of Neovim's window movement to do so.
In a popup window, hit `<C-w>T` to make the current popup window become a tab, or `<C-w>L` to make the popup window become a split to the right.

See: https://github.com/rmagatti/goto-preview/issues/8

**Comment by elkowar** [comment]
ohh, didn't know about that, very nice! Given that it's come up more than once, that might be worth mentioning in your README ^^
otherwise we can close this!

**Comment by rmagatti** [comment]
Yeah it is probably worth mentioning. I'll keep this open to track adding that to the readme. I'd be glad to review a PR too if you're up for it 😄
