### ISSUE TITLE
[BUG] Doesn't work with clojure-lsp attempt to index local 'data' nil

### ISSUE THREAD

**Issue by tami5** [rmagatti/goto-preview#42]
**Describe the bug**
When trying to use goto-preview with clojure lsp, I get the following error `...m/site/pack/packer/opt/goto-preview/lua/goto-preview.lua:15: attempt to index local 'data' (a nil value)`

**Expected behavior**
no error, normal behavior

**Baseline (please complete the following information):**
 - OS. e.g MacOs
 - Neovim version nightly
 - URL to your current config (if public)

**Comment by rmagatti** [comment]
Duplicate of #37
