### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by brianmoran** [rmagatti/goto-preview#43]
Is there a way to open a peek in a new buffer? Sometimes I have a peek open that I want to now have full window and/or in a split.

**Comment by rmagatti** [comment]
You can already do that. See #8 and #38.

**Comment by brianmoran** [comment]
OMG I'm so sorry.

**Comment by wookayin** [comment]
@brianmoran  Would you mind changing the title of this issue so that this can be more searchable? Thanks!

**Comment by wookayin** [comment]
BTW, I understand that #8 and #38 are about opening them into a new window (via `wincmd T` or `wincmd L`, etc.) --- I don't think it is opening a new **buffer**. In vim, it wouldn't be possible if the destination were the same file?

**Comment by rmagatti** [comment]
@wookayin yeah those issues solve it by manipulating the window. In Vim you can't open another window with the same buffer, but in Neovim you can. Opening in another _buffer_ would be outside of the scope of this plugin from what I can tell and I actually don't see any point in doing that myself.
