### ISSUE TITLE
Show filepath as the preview title?

### ISSUE THREAD

**Issue by lougreenwood** [rmagatti/goto-preview#52]
Really nice addon! It's helping me on my transition away from VSCode.

I wonder, did you consider showing the path to the file in the preview window "title" area?

Thanks again! 🙏

**Comment by rmagatti** [comment]
Hi, I'm glad you're enjoying it!

So, what exactly do you mean by the "window title area"?
 In my workflow if I need to know the filename of the buffer currently being previewed I just hit CTRL-G and that prints the current file name in my statusline.

**Comment by lougreenwood** [comment]
Sorry for the delay - I mean something like how Telescope shows a window title for it's views.

![Screenshot 43](https://user-images.githubusercontent.com/12051736/149626241-812b94a4-b935-4856-a077-f27248540967.png)

**Comment by rmagatti** [comment]
I see. This is technically possible, though maybe not how you'd expect. A floating window doesn't have a "title" property or anything like that afaik, telescope just draws its borders like that.

goto-preview would have to draw its borders differently per window, which it doesn't currently support but could.

I can see this being useful but there are also some annoyances like handling "long paths" and how to show that, one could maybe use shorten path to make this work I suppose.

**Comment by rmagatti** [comment]
It should already be the default, guess I forgot to close this issue.
The readme also has information on customizing where the title goes if that's something you want.

<img width="1082" alt="Screenshot 2023-04-14 at 2 04 16 PM" src="https://user-images.githubusercontent.com/2881382/232144460-ad31a369-a95f-4148-971d-a31fbd7d6f53.png">

**Comment by aksh1618** [comment]
For future visitors wanting to do this for references telescope preview: You can just set this option in your telescope config:

```lua
require('telescope').setup({ defaults = { dynamic_preview_title = true, }, }) 
```
