### ISSUE TITLE
[BUG] Exception in get_config when LSP responds without any data (vetur)

### ISSUE THREAD

**Issue by andersevenrud** [rmagatti/goto-preview#53]
**Describe the bug**
I get the following exception when triggering preview inside a `<template>` in Vue filetype when using the [vetur LSP](https://github.com/vuejs/vetur).

```
Error executing vim.schedule lua callback: ...site/pack/packer/start/goto-preview/lua/goto-preview.lua:18: attempt to index local 'range' (a nil value)
stack traceback:
        ...site/pack/packer/start/goto-preview/lua/goto-preview.lua:18: in function 'get_config'
        .../pack/packer/start/goto-preview/lua/goto-preview/lib.lua:220: in function 'handle'
        .../pack/packer/start/goto-preview/lua/goto-preview/lib.lua:254: in function 'handler'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:964: in function ''
        vim.lua: in function <vim.lua:0>
```

This works like expected inside a `<script>`  section, so this is definitely an issue with the LSP itself.

The `lib.logger.debug(vim.inspect(data))` statement gives `{}`, so it's no wonder why this fails.

So maybe add some additional checks here so that it doesn't fail with an exception?

**To Reproduce**
1. Create a new Vue file
2. Write a basic template
3. Set cursor above a component tag and trigger preview

**Expected behavior**
A popup, or nothing if no data available.

**Baseline (please complete the following information):**
 - `Linux aworkstation 5.15.10-arch1-1 #1 SMP PREEMPT Fri, 17 Dec 2021 11:17:37 +0000 x86_64 GNU/Linux`
 - `NVIM v0.7.0-dev+746-g95803f0e9`
 - [URL to your current config (if public)](https://github.com/andersevenrud/dotfiles/tree/master/.config/nvim)

**Comment by rmagatti** [comment]
Hey 👋 so from what I understand here the issue is just that I'm throwing an error instead of just handling the fact that the lsp server may return an empty table right? If that is correct #55 should help with that.

**Comment by andersevenrud** [comment]
Exactly :)

That PR took care of it. Thanks!
