### ISSUE TITLE
[BUG] Does not play well with stevearc/aerial.vnim

### ISSUE THREAD

**Issue by joehannes** [rmagatti/goto-preview#56]
**Describe the bug**
when triggering the default mapping "gpd", instead of previewing the definition,
nvim is throwing an error regarding another plugin, namely stevearc/aerial.nvim

**To Reproduce**
1. Install aerial.nvim alongside or clone [my config](https://github.com/joehannes-os/neovim-lua-config) after safeguarding yours
2. I don't tweak those a lot, so default settings should suffice
3. try to "gpd" on some usage of something ... (eg.: with cursor on the import of a React Component, in normal mode, press "gpd")
4. observe neovim throwing the above error ...

**Expected behavior**
I would like to see the actual preview of the definition of the import/thingy

**Screenshots**
![EF9CE19A-ACF5-4312-B00B-5C9CCD0C4403](https://user-images.githubusercontent.com/63741107/147787140-ab53d9ee-1928-4833-bc02-2d7db76035c8.png)

**Baseline (please complete the following information):**
 - OS. e.g `uname -a`: Darwin Kernel Version 21.2.0
 - Neovim version `nvim --version`: NVIM v0.7.0-dev+2267-gc46f7caad
 - URL to your current config (if public): https://github.com/joehannes-os/neovim-lua-config

**Additional context**
Justy a quick note: I dblchecked on the default mappings of aerial, and "gpd" doesn't seem to be one of them

**Comment by rmagatti** [comment]
Hey @joehannes goto-preview works by creating floating windows, I have never used aerial.nvim but from the looks of it this is probably an issue to open with that repo instead of goto-preview, at least that's what it looks to me at first glance. I will dig a bit further when I get a chance.

**Comment by joehannes** [comment]
hey @rmagatti :-) cool ... my thought was, that because it seems aerial doesn't have anything bound to "gpd" ... and the bug happens on "gpd" ... I thought while "goto-preview" is checking the buffers for whatever reason ... and so on ... but since you already say it's based on floating windows ... however: if it was due to the origin of the <cword> or something like that ...??? looking things up in a buffer there and somehow the current buffer would boil down to a hidden aerial buffer or something .. (because strangely enough, I don't even have the aerial outline opened when I get that err).
I'll ping the guys at aerial.nvim as well to let them know

**Comment by joehannes** [comment]
hehey :-)

just to let you guys know, stevearc from aerial.nvim did some defensive coding and [it solved the issue](https://github.com/stevearc/aerial.nvim/issues/38) ...

**Comment by rmagatti** [comment]
Got it. It's one thing @stevearc said that stood out to me was the buffer being deleted part. Pretty sure goto-preview isn't deleting it _but_ depending on your vim settings, like if you don't have `set hidden`, buffers would be deleted automatically upon being unloaded. This might explain what's happening. Keep in mind this is just a guess for now.

**Comment by stevearc** [comment]
Yeah, I wouldn't assume that it's any sort of problem with goto-preview. Likely as you said, just some interaction with `hidden` or `bufhidden`. You're probably safe to close this out
