### ISSUE TITLE
Ability to modify file in floating window, without the need to full open it

### ISSUE THREAD

**Issue by Huray-hub** [rmagatti/goto-preview#58]
**Is your feature request related to a problem? Please describe.**
Ability to modify a file in a floating window, without the need to fully open it

**Describe the solution you'd like**
I would like to do some small changes to the floating window (ex. add a property to a class), save, then close (ideally just with the escape key), without fully opening it to split.

Inspiration: Visual Studio (the IDE not the text editor)

**Comment by rmagatti** [comment]
Hi, thanks for the issue submission.
That is already possible.
https://user-images.githubusercontent.com/2881382/154138952-b4ce4589-0d2f-4921-b996-5c97f06bc834.mov
