### ISSUE TITLE
[FEATURE] Press <Esc> while preview buffer is focused to close

### ISSUE THREAD

**Issue by Zane-** [rmagatti/goto-preview#61]
**Is your feature request related to a problem? Please describe.**
Closing buffers is unintuitive compared to other plugins

**Describe the solution you'd like**
Map <Esc> to close a preview buffer when selected

**Comment by Zane-** [comment]
Thanks for the explanation, I realized it's just a normal window, so <c-w><c-q> works fine!

**Comment by gbcreation** [comment]
Here is the `post_open_hook` I use to close the preview window with `<Esc>`:

```lua
post_open_hook = function ()
    -- Close the current preview window with <Esc>
    vim.keymap.set(
        'n',
        '<Esc>',
        function()
            local current_win_handle = vim.api.nvim_get_current_win()
            if vim.api.nvim_win_get_var(current_win_handle, 'is-goto-preview-window') == 1 then
                vim.api.nvim_win_close(current_win_handle, true)
            end
        end,
        { buffer = true }
    )
end,

```

**Comment by jaycle** [comment]
The above solution is great if the option `focus_on_open` is set to `false` (default is `true`). But if you use the default mapping, you should use the first argument to the `post_open_hook` to scope the keybind to the floating buffer. If not, the keybind will survive to the parent buffer, which results in errors on subsequent uses of `<Esc>`. 

e.g.
```lua
  post_open_hook = function(buff, win)
    vim.keymap.set('n', '<Esc>', function() 
      if vim.api.nvim_win_is_valid(win) then
        vim.api.nvim_win_close(win, true)
      end
    end, { buffer = buff })
  end,
})
```
