### ISSUE TITLE
Highlight group?

### ISSUE THREAD

**Issue by AGou-ops** [rmagatti/goto-preview#62]
What `highlight group` does `goto-preview` use? It seems different.

<img width="1548" alt="image" src="https://user-images.githubusercontent.com/57939102/169845510-dff3f65e-0c74-40de-97ef-9212e3cc9640.png">

I don't want to use this `italic` font.

**Comment by rmagatti** [comment]
I don't actually set any highlight groups. Maybe your config sets specific things for floating windows?

**Comment by AGou-ops** [comment]
Oh, I have found it. `:hi NormalFloat`

Thanks for your directions!
