### ISSUE TITLE
Different color theme in flat window

### ISSUE THREAD

**Issue by divan** [rmagatti/goto-preview#64]
Hey, thank you for the fantastic plugin.

Somehow color theme in the float windows are different from my main theme (it is with black bg). I have quite a number of plugins that might influence the color (like `shade` that shades inactive windows, but I disabled it for trying this one).

Any ideas why this might be the case or any hints where to look?
Thanks!

![Screenshot 2022-06-17 at 15 59 48](https://user-images.githubusercontent.com/880202/174303376-bf4c1b07-db7b-4be6-a599-244a78f9e5d2.png)

**Comment by rmagatti** [comment]
@divan thanks for the kind words!

Since these are floating windows they probably just have a different highlight group.
If you'd like to force that change you can set a normal highlight group for the floating windows with the `post_open_hook`.

Ex (untested):
```lua
post_open_hook = function(_, win)
  vim.api.nvim_win_set_option(win, "winhighlight", "Normal:")
end
```

**Comment by divan** [comment]
That's seem to work.
I still don't understand why it happened in a first place. Is it something wrong with my config or with the color theme or with plugin config?

Thank you for help, closing for now.

**Comment by rmagatti** [comment]
Your theme probably just has a different background colour for floating windows.
