### ISSUE TITLE
[Suggestion] Remove vim.inspect

### ISSUE THREAD

**Issue by adoyle-h** [rmagatti/goto-preview#75]
There are too many `vim.inspect` for debug.

It is unnecessary that the handler always inspect the result.

https://github.com/rmagatti/goto-preview/blob/a5af27cff485b325f0ef2dcdf55ae51faed05cba/lua/goto-preview/lib.lua#L282-L291

**Comment by rmagatti** [comment]
Is this causing some sort of issue though?

**Comment by adoyle-h** [comment]
No. So it is just a suggestion.
