### ISSUE TITLE
[FEATURE] Closing `n+1` preview should move the focus to the `n` preview

### ISSUE THREAD

**Issue by D00mch** [rmagatti/goto-preview#77]
**Describe the solution you'd like**
If I open previews `a`,`b`, and `c`, closing `c` should put my focus on b; closing b — on `a`.

**Describe alternatives you've considered**
I have a function that I do`vim.keymap.set` with the local buffer inside the `post_open_hook`:

```lua:
local function close_and_move_focus_on_prev()
  local prev_win = vim.fn.winnr()
  vim.cmd("wincmd p")
  return vim.cmd((prev_win .. "wincmd q"))
end
```

**Additional context**
On the gif below I do:
1. Show that I commented my buffer keymap.
2. Open project and demonstrate, that after closing second preview I didn't go to the first one;
3. Reopen config and uncomment my `close_and_move_focus_on_prev` function;
4. Open project again and demonstrate that the problem is fixed.

(my config is in fennel).

![demo](https://user-images.githubusercontent.com/14236531/206113615-0ab9bb82-c9f8-4fc7-9e01-dc7466189d73.gif)

**Comment by rmagatti** [comment]
Hey 👋 that's weird. The order seems to be kept correctly for me here.

![2022-12-08 11 15 04](https://user-images.githubusercontent.com/2881382/206533953-3200c657-86e7-4acf-85ae-4b9ce1c2e93b.gif)

**Comment by D00mch** [comment]
I close windows with mapping that does `:q<Cr>`. Don't know what may cause this behavior. Lets maybe wait for a while if anyone has the same problem.

**Comment by rmagatti** [comment]
I have the same exact mapping `<leader>q :q<CR>` so that shouldn't be the cause.

**Comment by spocke** [comment]
I have the same issue but I need to go three levels deep.

**Comment by Tebro** [comment]
Same issue here, if using `<C-w>c` it doesn't go back at all, if you chain three deep then `:q` will only go back once. I guess there is a variable `last` that gets updated instead of a stack?
