### ISSUE TITLE
Support for opening buffer in the active preview window in the background as a normal buffer

### ISSUE THREAD

**Issue by sahilsehwag** [rmagatti/goto-preview#8]
Sometimes we are navigating the code and while digging some definitions we find some important symbol that we need to understand more carefully(like it keeping it aside and thinking something like I'll come back to this).

It would be better if we can have support to open the buffer in active preview window to a normal buffer (without loosing the focus of floating preview)

**Comment by rmagatti** [comment]
hey @sahilsehwag there's some support for this with regular Vim window movements.
If you have a preview float focused, you can do `<C-w>j` for example to turn that float into a regular split window.

That said there are some UI issues that happen when you do that currently since the borders are not removed. I can probably fix the UI issues in the plugin though.

Another thing to note is that the plugin still keeps track of that window, so if you trigger the binding to close all the windows, that window you just moved to a split would also close.

Could potentially also be tweaked but I'd like to put more thought into what would be a desired workflow first.

**Comment by rmagatti** [comment]
Just to give you an example of what I mean.

![2021-06-11 01 55 23](https://user-images.githubusercontent.com/2881382/121652080-88716e00-ca58-11eb-811c-677ec61d8e25.gif)

**Comment by sahilsehwag** [comment]
Hey, this satisfies one of the flow, another flow that would be great to have is(I am not sure if vim supports it), open the buffer in background without losing/closing the current preview window(s) ?

**Comment by rmagatti** [comment]
I see, you could add mappings to do `:badd %` or something similar to add a buffer to the buffer list based on the currently focused floating preview's buffer but not switch to it or lose focus on your current flow.

I think this would be possible to support in goto-preview as part of the default mappings, those assume a particular flow ofc, but if you're opting into using default mappings, that's probably okay/expected.

**Comment by rmagatti** [comment]
Hey. So one way you could make this happen is adding your own mapping in the `post_open_hook` function to send the preview window to a tag `CTRL + w T` would do that for example. The downside here is you'd focus the newly created tab, but you could always navigate back. Either that or find a way to not focus a tab on creation.

**Comment by rmagatti** [comment]
Closing this as it is technically supported and really just depends on how one wants to use do it.

**Comment by rmagatti** [comment]
@shaeinst ah right, I think I was wrong before, instead of `:badd %`, all you need to do is `set buflisted` while having the preview window focused. So something like this for the `post_open_hook` function.

```lua
  post_open_hook = function()
    vim.api.nvim_buf_set_option(vim.api.nvim_get_current_buf(), "buflisted")
  end
```

**Comment by shaeinst** [comment]
thanks. 
i think vim.api.nvim_buf_set_option takes three arguments
>     vim.api.nvim_buf_set_option(vim.api.nvim_get_current_buf(), "buflisted")
so following would work
```lua 
  	post_open_hook = function()
		-- add preview window to buffer list
		local buffer_num = vim.api.nvim_get_current_buf() -- current buffer
		vim.api.nvim_buf_set_option(buffer_num, "buflisted", true)
	end;

```
