### ISSUE TITLE
Getting "Invalid key" error when go to definition

### ISSUE THREAD

**Issue by proivk** [rmagatti/goto-preview#94]
**Describe the bug**
Error message each time I go to definition.

**To Reproduce**
1. Open file (*.go file in my case)
2. gpd on some method or variable

**Expected behavior**
Pop up window with definition of method or variable

**Screenshots**
```
Error executing vim.schedule lua callback: .../pack/packer/start/goto-preview/lua/goto-preview/lib.lua:115: invalid key: title
stack traceback:
        [C]: in function 'nvim_open_win'
        .../pack/packer/start/goto-preview/lua/goto-preview/lib.lua:115: in function 'open_floating_win'
        .../pack/packer/start/goto-preview/lua/goto-preview/lib.lua:253: in function 'handle'
        .../pack/packer/start/goto-preview/lua/goto-preview/lib.lua:284: in function 'handler'
        ...w/Cellar/neovim/0.8.3/share/nvim/runtime/lua/vim/lsp.lua:1383: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```
**Baseline (please complete the following information):**
 - OS. e.g `uname -a`:
 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103 arm64
 - Neovim version `nvim --version`
 NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3

 - URL to your current config (if public)
```
    use {
      'rmagatti/goto-preview',
      config = function()
        require('goto-preview').setup {
          default_mappings = true,
          ---preview_window_title = { enable = true, position = "left" },
        }
      end
    }
```

**Additional context**
gpr works well though. gpi do nothing

**Comment by rmagatti** [comment]
Oh, I suppose the new title feature is only on nightly. I'll add some code to make it backwards compatible. Thanks for flagging

**Comment by Fangjun-Zhou** [comment]
> Mind testing out the branch in the linked PR @proivk ?

I have the same issue, I'll can test the PR branch latter.

**Comment by Fangjun-Zhou** [comment]
The PR branch solves this issue.
But I have a question unrelated to this issue: Can I open the previewed position in the current window?

**Comment by rmagatti** [comment]
Thanks for testing it out, I've replied to your question in the linked issue.

**Comment by proivk** [comment]
Works perfectly.
Thank you!
